updated the bash scripts for "nass" and the helper scripts

diff --git a/assemble b/assemble
--- a/assemble
+++ b/assemble
@@ -3,11 +3,11 @@
 gcc Assembler/*.c
 rc=$?
 if [ $rc -ne 0 ]; then
-    echo "Error compiling assembler"
+    echo "Error compiling assembler" 1>&2
     exit 1
 fi
 ./a.out $1 $2 $3 $4 $5
 if [ $? -ne 0 ]; then
-    echo "Error assembling code"
+    echo "Error assembling code" 1>&2
     exit 1
 fi
diff --git a/simulate b/simulate
--- a/simulate
+++ b/simulate
@@ -4,12 +4,12 @@
 gcc Simulator/*.c
 rc=$?
 if [ $rc -ne 0 ]; then
-    echo "Error building simulator"
+    echo "Error building simulator" 1>&2
     exit 1
 fi
 ./a.out $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14}
 rc=$?
 if [ $rc -ne 0 ]; then
-    echo "Simulation finished with errors"
+    echo "Simulation finished with errors" 1>&2
     exit 1
 fi
