apparently you can declare functions in header files lol also updated some pointless stuff, tested assemly and oh yeah i finished the disk test

diff --git a/assemble b/assemble
--- a/assemble
+++ b/assemble
@@ -3,7 +3,11 @@
 gcc Assembler/*.c
 rc=$?
 if [ $rc -ne 0 ]; then
-    echo "Error"
+    echo "Error compiling assembler"
     exit 1
 fi
 ./a.out $1 $2 $3 $4 $5
+if [ $? -ne 0 ]; then
+    echo "Error assembling code"
+    exit 1
+fi
diff --git a/simulate b/simulate
--- a/simulate
+++ b/simulate
@@ -4,11 +4,12 @@
 gcc Simulator/*.c
 rc=$?
 if [ $rc -ne 0 ]; then
-    echo "Error"
+    echo "Error building simulator"
     exit 1
 fi
 ./a.out $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14}
 rc=$?
-echo
-echo Simulator: program returned $rc
-echo 
+if [ $rc -ne 0 ]; then
+    echo "Simulation finished with errors"
+    exit 1
+fi
