addeed initial assembly decoding capabilities, updated readme

diff --git a/assemble b/assemble
--- a/assemble
+++ b/assemble
@@ -1,4 +1,9 @@
 #!/bin/bash
 
 gcc Assembler/*.c
-./a.out
+rc=$?
+if [ $rc -ne 0 ]; then
+    echo "Error"
+    exit 1
+fi
+./a.out $1
diff --git a/simulate b/simulate
--- a/simulate
+++ b/simulate
@@ -1,4 +1,9 @@
 #!/bin/bash
 
 gcc Simulator/*.c
-./a.out
+rc=$?
+if [ $rc -ne 0 ]; then
+    echo "Error"
+    exit 1
+fi
+./a.out $1 $2 $3 $4 $5 $6 $7 $8 $9 
